export const ItemDB = {
    "Tasks": {
        "task-telescope": "Telescope",
        "task-chart": "Chart Course",
        "task-oxygen": "O2 Canisters",
        "task-tree": "Tree Monitor",
        "task-temp1": "Record Temp 1",
        "task-temp2": "Record Temp 2",
        "task-artifacts": "Store Artifacts",
        "task-simonsays": "Simon Says",
        "task-counting": "Unlock Manifolds",
        "task-medscan": "Medscan",
        "task-keys": "Keys",
        "task-drill": "Drill",
        "task-id": "Swipe Card",
        "task-pass": "Scan Pass",
        "task-node1": "Node 1",
        "task-node2": "Node 2",
        "task-node3": "Node 3",
        "task-node4": "Node 4",
        "task-node5": "Node 5",
        "task-node6": "Node 6",
        "task-samples": "Inspect Samples",
        "task-waterwheel1": "Water Wheel 1",
        "task-waterwheel2": "Water Wheel 2",
        "task-waterwheel3": "Water Wheel 3",
        "task-router": "Reboot Router",
        "task-garbage": "Empty Garbage",
        "task-weapons": "Weapons",
        "task-waterjug1": "Water Jug 1",
        "task-waterjug2": "Water Jug 2",
        "task-download1": "Download 1",
        "task-download2": "Download 2",
        "task-download3": "Download 3",
        "task-download4": "Download 4",
        "task-download5": "Download 5",
        "task-upload": "Upload",
        "task-wires1": "Wires 1",
        "task-wires2": "Wires 2",
        "task-wires3": "Wires 3",
        "task-wires4": "Wires 4",
        "task-wires5": "Wires 5",
        "task-wires6": "Wires 6",
        "task-nodeswitch": "Node Switches"
    },
    "Sabotages": {
        "sab-reactor-left": "Left Reactor",
        "sab-reactor-right": "Right Reactor",
        "sab-electric": "Lights Panel"
    },
    "Utilities": {
        "util-button": "Emergency Button",
        "util-admin": "Admin Table",
        "util-vitals": "Vitals",
        "util-cams": "Cameras",
        "util-computer": "Freeplay Laptop"
    }
};