export const ItemDB = {
    "Tasks": {
        "task-id": "Card Swipe",
        "task-keys": "Keys",
        "task-pass": "Scan Pass",
        "task-simonsays": "Simon Says",
        "task-fuel1": "Gas Canister",
        "task-fuel2": "Gas Output 1",
        "task-fuel3": "Gas Output 2",
        "task-waterwheel1": "Water Wheel 1",
        "task-waterwheel2": "Water Wheel 2",
        "task-waterwheel3": "Water Wheel 3",
        "task-samples": "Inspect Samples",
        "task-waterjug1": "Water Jug 1",
        "task-waterjug2": "Water Jug 2",
        "task-node": "Weather Node",
        "task-router": "Reboot Router",
        "task-tree": "Monitor Tree",
        "task-counting": "Unlock Manifolds",
        "task-artifacts": "Sort Artifacts",
        "task-oxygen": "O2 Canisters",
        "task-garbage": "Garbage",
        "task-chart": "Chart Course",
        "task-medscan": "Medscan",
        "task-weapons": "Weapons",
        "task-telescope": "Telescope",
        "task-drill": "Drill",
        "task-temp1": "Temp 1",
        "task-temp2": "Temp 2",
        "task-nodeswitch": "Node Switches",
        "task-code": "Enter ID Code",
        "task-divert1": "Divert Power 1",
        "task-divert2": "Divert Power 2",
        "task-plants1": "Get Water Can",
        "task-plants2": "Water Plants",
        "task-crystal": "Assemble Artifact",
        "task-sort": "Sort Samples",
        "task-shields": "Prime Shields",
        "task-weather": "Measure Weather",
        "task-vending": "Vending Machine",
        "task-process": "Process Data",
        "task-diagnostics": "Run Diagnostics",
        "task-align1": "Align Engine 1",
        "task-align2": "Align Engine 2",
        "task-stabilize": "Stabilize Steering",
        "task-showers": "Fix Showers",
        "task-burger": "Make Burger",
        "task-decontaminate": "Decontaminate",
        "task-rifles1": "Rifles 1",
        "task-rifles2": "Rifles 2",
        "task-pistols1": "Pistols 1",
        "task-pistols2": "Pistols 2",
        "task-records1": "Records Folder",
        "task-records2": "Records Shelf",
        "task-mannequin": "Dress Mannequin",
        "task-toilet": "Clean Toilet",
        "task-towels1": "Towel Basket",
        "task-towels2": "Wet Towel",
        "task-towels3": "Dry Towel",
        "task-towels4": "Bunched Towel",
        "task-towels5": "Hanging Towel",
        "task-stabilize2": "Steering (Airship)",
        "task-ruby": "Polish Ruby",
        "task-tapes": "Rewind Tapes",
        "task-photos": "Develop Photos",
        "task-garbage2": "Blue Trash (Airship)",
        "task-garbage3": "Grey Trash (Airship)",
        "task-garbage4": "Green Trash (Airship)",
        "task-garbage5": "Trash Part 2 (Airship)",
        "task-safe": "Unlock Safe",
        "task-breakers": "Reset Breakers",
        "task-fans1": "Start Fans 1",
        "task-fans2": "Start Fans 2",
        "task-distributor": "Calibrate Distributer"
    },
    "Sabotages": {
        "sab-electric": "Lights Panel",
        "sab-reactorleft": "Left Reactor",
        "sab-reactorright": "Right Reactor",
        //"sab-oxygen1": "O2 Panel 1",
        //"sab-oxygen2": "O2 Panel 2",
        "sab-comms": "Comms Panel"
    },
    "Utilities": {
        "util-button1": "Skeld/Polus Button",
        "util-button2": "Mira Button",
        "util-admin": "Admin Table",
        "util-vitals": "Vitals",
        "util-computer": "Freeplay Laptop",
        "util-room": "Room",
        "util-player": "Dummy",
        "util-vent1": "Skeld/Mira Vent",
        "util-vent2": "Polus Vent",
        "util-cam": "Camera",
        "util-cams": "Polus Cams",
        "util-cams2": "Skeld Cams",
        "util-cams3": "Airship Cams",
        "util-spawn1": "Initial Spawn",
        "util-spawn2": "Meeting Spawn"
    },
    "Rooms": {
        "room-polusadmin": "Polus Admin",
        "room-poluscomms": "Polus Comms",
        "room-poluselectric": "Polus Electric",
        "room-polusmedbay": "Polus Medbay",
        "room-poluso2": "Polus O2",
        "room-polusspecimen": "Polus Specimen",
        "room-polusspecimenhallway1": "Polus Spec Hall 1",
        "room-polusspecimenhallway2": "Polus Spec Hall 2",
        "room-polusstorage": "Polus Storage",
        "room-polusweapons": "Polus Weapons",
        "room-skeldcafe": "Skeld Cafe",
        "room-skeldelectric": "Skeld Electric",
        "room-skeldengine1": "Skeld Engine 1",
        "room-skeldengine2": "Skeld Engine 2",
        "room-skeldmedbay": "Skeld Medbay",
        "room-skeldadminhallway": "Skeld Admin Hall",
        "room-skeldnavhallway": "Skeld Nav Hall",
        "room-skeldo2": "Skeld O2",
        "room-skeldreactorhallway": "Skeld Reactor Hall",
        "room-skeldsecurity": "Skeld Security",
        "room-skeldstorage": "Skeld Storage",
        "room-skeldshieldhall": "Skeld Shields Hall",
        "room-miramedbaycomms": "Mira Medbay / Comms",
        "room-mirayhall": "Mira Y Hall",
        "room-mirareactor": "Mira Reactor",
        "room-miralaunchpad": "Mira Launchpad",
        "room-mirao2admin": "Mira O2 / Admin",
        "room-miracafe": "Mira Cafe",
        "room-dropship": "Dropship",
        "room-dropshiptop": "Dropship Top",
        "room-dropshiprear": "Dropship Rear",
        "room-dropshipramp": "Dropship Ramp",
        "room-airshiparmory": "Airship Armory",
        "room-airshipbrig": "Airship Brig",
        "room-airshipcockpit": "Airship Cockpit",
        "room-airshipcomms": "Airship Comms",
        "room-airshipejection": "Airship Plank",
        "room-airshipelctrical": "Airship Electrical",
        "room-airshipengines": "Airship Engines",
        "room-airshipgap": "Airship Gap",
        "room-airshiphallway": "Airship Hallway 1",
        "room-airshipkitchen": "Airship Kitchen",
        "room-airshiplounge": "Airship Lounge",
        "room-airshipmainhall": "Airship Hallway 2",
        "room-airshipmedbay": "Airship Medbay",
        "room-airshipmeeting": "Airship Meeting",
        "room-airshipmeeting2": "Airship Meeting 2",
        "room-airshipoutside": "Airship Balcony",
        "room-airshipportraits": "Airship Portraits",
        "room-airshipsecurity": "Airship Security",
        "room-airshipshowers": "Airship Showers",
        "room-airshipstorage": "Airship Storage",
        "room-airshipvault": "Airship Vault",
        "room-airshipvent": "Airship Shaft",
        "room-airshiprecords": "Airship Records"
    },
    "Decoration": {
        "dec-rock1": "Rock 1",
        "dec-rock2": "Rock 2",
        "dec-rock3": "Rock 3",
        "dec-rock4": "Rock 4",
        "dec-rock5": "Rock 5",
        "dec-snowman": "Snowman",
        "dec-snowmanded": "Dead Snowman",
        "dec-vending2": "Vending Machine 1",
        "dec-vending3": "Vending Machine 1",
        "dec-barrier": "Barrier",
        "dec-bench1": "Bench 1",
        "dec-bench2": "Bench 2",
        "dec-table1": "Table 1",
        "dec-table2": "Table 2",
        "dec-table3": "Table 3",
        "dec-table4": "Table 4",
        "dec-table5": "Table 5",
        "dec-table6": "Table 6",
        "dec-table7": "Table 7",
        "dec-table8": "Table 8",
        "dec-table9": "Table 9",
        "dec-table10": "Table 10",
        "dec-table11": "Table 11",
        "dec-table12": "Table 12",
        "dec-table13": "Table 13",
        "dec-table14": "Table 14",
        "dec-engine1": "Skeld Engine",
        "dec-box1": "Box 1",
        "dec-box2": "Box 2",
        "dec-box3": "Box 3",
        "dec-box4": "Box 4",
        "dec-box5": "Box 5",
        "dec-box6": "Box 6",
        "dec-box7": "Box 7",
        "dec-box8": "Box 8",
        "dec-box9": "Box 9",
        "dec-divingboard": "Diving Board",
        "dec-projector": "Projector",
        "dec-bed1": "Bed 1",
        "dec-bed2": "Bed 2",
        "dec-bathroom": "Bathroom Stalls",
        "dec-cargo1": "Airship Cargo",
        "dec-chair1": "Chair 1",
        "dec-chair2": "Chair 2",
        "dec-chair3": "Chair 3",
        "dec-panel1": "Panel 1",
        "dec-panel2": "Panel 2",
        "dec-pool1": "Pool Table 1",
        "dec-pool2": "Pool Table 2",
        "dec-scale": "Scale",
        "dec-shelf1": "Kitchen Shelf",
        "dec-shelf2": "Bookshelf",
        "dec-statue1": "Gun Statue",
        "dec-statue2": "Sword Statue",
        "dec-stove1": "Stove 1",
        "dec-stove2": "Stove 2"
    }
};